# Generated by Django 2.0.6 on 2018-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_auto_20180710_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='diesel_exist',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='jobkg_exist',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='diesel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='jobkg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='diesel_url',
            field=models.URLField(null=True),
        ),
    ]
