# Generated by Django 2.0.6 on 2018-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0020_auto_20180713_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='diesel_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='jobkg_url',
        ),
        migrations.AddField(
            model_name='publication',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_service',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
