# Generated by Django 2.0.6 on 2018-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0021_auto_20180713_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
