# Generated by Django 2.0.6 on 2018-07-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0022_publication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='last_published',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
