version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hr_crm
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: db
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hr_crm
